package org.palladiosimulator.analyzer.slingshot.simulation.events;

/**
 * This interface describes an event that is happening within the system.
 * 
 * @author Julijan Katic
 */
public interface DESEvent {

	/**
	 * @return the id of this event. Typically generated by a
	 *         {@link java.util.UUID}.
	 */
	String getId();

	/**
	 * @return the simulation time for this event.
	 */
	double time();

	/**
	 * Resets the simulation time in the event.
	 */
	void setTime(double time);
	
	/**
	 * @return The delay, i.e. how much time to wait until
	 */
	double getDelay();
}
